name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} on ${{ matrix.os }} (${{ matrix.composer-options }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        experimental:
          - false
        composer-options:
          - ""
          - "--prefer-lowest"
        include:
          - php-version: "8.1"
            os: ubuntu-latest
            experimental: true
            composer-options: "--ignore-platform-req=php"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Validate composer.json and composer.lock
        run: composer validate
        
      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pcntl, posix
        
      - name: Install dependencies
        run: composer update
          --prefer-dist
          --no-progress
          ${{ matrix.composer-options }}

      - name: Run tests
        run: composer test
